name: Sync Image Rabbitpro to Aliyun Example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git pull
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.cn-guangzhou.aliyuncs.com
        username: ${{ secrets.ALI_USERNAME }}
        password: ${{ secrets.ALI_PASSWORD }}
        logout: false

    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
         skopeo copy docker://docker.io/hslr/sun-panel:1.4.0 docker://registry.cn-guangzhou.aliyuncs.com/rns/sun-panel:1.4.0
         skopeo copy docker://docker.io/shufflewzc/qrbbitpro:latest docker://registry.cn-guangzhou.aliyuncs.com/rns/qrbbitpro:latest
      # 使用 skopeo 工具将镜像同步到阿里云个人仓库中
